test:
  image: python:3.7-stretch
  before_script:
  - cd api_server/
  - apt update -q
  - apt install -qy sqlite3 libmariadbclient-dev
  - pip3 install -r requirements.txt
  - cp CONFIGURATION.py{.example,}
  script:
  - pytest -vv
