test:
  before_script:
  - apt update -q
  - apt install -qy sqlite3 python3 python3-pip libmariadbclient-dev
  - pip3 install -r requirements.txt
  - cd api-server
  - cp unit_test_settings.py{.example,}
  - cp settings.py{.example,}
  script:
  - pytest
