image: python:3.7-stretch

cache:
  paths:
    - .cache/pip - venv/

# We declare a job that gitlab ignores and put a YAML anchor
# See https://gitlab.com/gitlab-org/gitlab-ce/issues/15403#note_27079119
.setup_test_jobs: &before_test_job
  before_script:
    - uname -a
    - python -V
    - pip install virtualenv
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - pip install -r api_server/requirements.txt

stages:
  - test
  - deploy_dev

python_check_for_vuln_deps:
  stage: test
  <<: *before_test_job # We reference our previous anchor
  script:
  - cd api_server/
  - pip install safety
  - safety check -r requirements.txt
  - safety check

python_unit_test:
  stage: test
  <<: *before_test_job # We reference our previous anchor
  script:
  - cd api_server/
  - pytest test/unit -vv

python_integration_test:
  stage: test
  <<: *before_test_job # We reference our previous anchor
  script:
  - cd api_server/
  - apt update -q
  - apt install -qy sqlite3 libmariadbclient-dev
  - pytest test/integration -vv

python_coverage:
  stage: test
  <<: *before_test_job # We reference our previous anchor
  script:
  - cd api_server/
  - pip install pytest-cov
  - pytest -vv --cov=src --cov-report=html --cov-report=term --cov-fail-under=80
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  artifacts:
    paths:
      - api_server/htmlcov/

deploy_dev:
  stage: deploy_dev
  script:
    - docker-compose build
    - docker-compose down
    - docker-compose up -d --force-recreate
  only:
    - master
  tags:
    - dev
