image: python:3.7-stretch

cache:
  paths:
    - ~/.cache/pip 

# We declare a job that gitlab ignores and put a YAML anchor
# See https://gitlab.com/gitlab-org/gitlab-ce/issues/15403#note_27079119
.setup_test_jobs: &before_test_job
  before_script:
    - pip install -r api_server/requirements.txt

stages:
  - test
  - build
  - deploy


angular_try_build:
  stage: build
  image: node:10.16.0-stretch-slim
  before_script:
    - cd frontend_angular/
    - NG_CLI_ANALYTICS=ci npm install -g @angular/cli@8.0.1
    - npm install
  script:
    - cp src/app/config/auth.config.ts{.example,}
    - rm src/app/config/auth.config.template.ts
    - ng build --prod

python_check_for_vuln_deps:
  stage: test
  # <<: *before_test_job # We reference our previous anchor
  script:
  - cd api_server/
  - pip install safety
  - safety check -r requirements.txt
  - safety check

python_unit_test:
  stage: test
  <<: *before_test_job # We reference our previous anchor
  script:
  - cd api_server/
  - pytest test/unit -vv

python_integration_test:
  stage: test
  <<: *before_test_job # We reference our previous anchor
  script:
  - cd api_server/
  - apt update -q
  - apt install -qy sqlite3 libmariadbclient-dev
  - pytest test/integration -vv

python_coverage:
  stage: test
  <<: *before_test_job # We reference our previous anchor
  script:
  - cd api_server/
  - pip install pytest-cov
  - pytest -vv --cov=src --cov-report=html --cov-report=term --cov-fail-under=80
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  artifacts:
    paths:
      - api_server/htmlcov/

deploy_dev:
  stage: deploy
  script:
    - docker-compose -f docker-compose-deploy.yml build
    - docker-compose -f docker-compose-deploy.yml down
    - docker-compose -f docker-compose-deploy.yml up --force-recreate -d 
  only:
    - master
  tags:
    - dev
    
deploy_prod:
  stage: deploy
  when: manual
  script:
    - systemctl stop emperor.uwsgi.service
    - cd api_server/
    - pip3 install -r ./requirements.txt
    - mibdump.py CISCO-VLAN-MEMBERSHIP-MIB IF-MIB CISCO-MAC-AUTH-BYPASS-MIB
    - cp ../openapi/spec.yaml ./openapi/spec.yaml
    - cat config/CONFIGURATION.template.py | envsubst | tee config/CONFIGURATION.py
    - ln -s -t /etc/uwsgi/vassals/ uwsgi.ini
    - systemctl start emperor.uwsgi.service
  only:
    - master
  tags:
    - adh6-prod
