image: python:3.7-stretch

cache:
  paths:
    - ~/.cache/pip 

# We declare a job that gitlab ignores and put a YAML anchor
# See https://gitlab.com/gitlab-org/gitlab-ce/issues/15403#note_27079119
.setup_test_jobs: &before_test_job
  before_script:
    - pip install -r api_server/requirements.txt

stages:
  - build
  - deploy

angular_try_build:
  stage: build
  image: node:10.16.0-stretch-slim
  before_script:
    - apt update && apt-get -y install gettext-base
    - cd frontend_angular/
    - NG_CLI_ANALYTICS=ci npm install -g @angular/cli@8.0.1
    - npm install
  script:
    - cp src/app/config/auth.config.ts{.example,}
    - rm src/app/config/auth.config.template.ts
    - ng build --prod
  environment:
    name: development
    url: https://adh6-dev.minet.net/

angular_build_prod:
  stage: build
  image: node:10.16.0-stretch-slim
  before_script:
    - apt update && apt-get -y install gettext-base
    - cd frontend_angular/
    - NG_CLI_ANALYTICS=ci npm install -g @angular/cli@8.0.1
    - npm install
  script:
    - cat src/app/config/auth.config.template.ts | envsubst | tee src/app/config/auth.config.ts
    - rm src/app/config/auth.config.template.ts
    - ng build --prod
  artifacts:
    paths:
    - frontend_angular/dist/
    expire_in: 1 day
  environment:
    name: production
    url: https://adh6.minet.net/

deploy_dev:
  stage: deploy
  script:
    - docker-compose -f docker-compose-deploy.yml build
    - docker-compose -f docker-compose-deploy.yml down
    - docker-compose -f docker-compose-deploy.yml up --force-recreate -d 
  only:
    - master
  environment:
    name: development
    url: https://adh6-dev.minet.net/
  tags:
    - dev

deploy_prod_front:
  stage: deploy
  when: manual
  script:
    - cp -r frontend_angular/dist/* /var/www/
  environment:
    name: production
    url: https://adh6.minet.net/
  tags:
    - adh6-prod
    - adh6-frontend

deploy_prod_backend:
  stage: deploy
  when: manual
  before_script:
    - sudo systemctl stop emperor.uwsgi.service
    - cd api_server/
    - sudo pip3 install -r ./requirements.txt
  script:
    - /usr/local/bin/mibdump.py CISCO-VLAN-MEMBERSHIP-MIB IF-MIB CISCO-MAC-AUTH-BYPASS-MIB
    - cp ../openapi/spec.yaml ./openapi/spec.yaml
    - cat config/CONFIGURATION.template.py | envsubst | tee config/CONFIGURATION.py
    - python3 manage.py db upgrade
    - cat uwsgi-prod.template | envsubst | tee uwsgi-prod.ini
    - sudo rm /etc/uwsgi/vassals/adh6_api.ini
    - sudo ln -s $(pwd)/uwsgi-prod.ini /etc/uwsgi/vassals/adh6_api.ini
    - sudo systemctl start emperor.uwsgi.service
  only:
    - master
  environment:
    name: production
    url: https://adh6.minet.net/
  tags:
    - adh6-prod
    - adh6-backend
