test:
  before_script:
  - cd api_server/
  - apt update -q
  - apt install -qy sqlite3 python3 python3-pip libmariadbclient-dev
  - pip3 install -r requirements.txt
  - cp CONFIGURATION.py{.example,}
  script:
  - pytest -vv
