version: '3.2'
services:
  # frontend_angular is a web server that provides the JS to the clients.
  frontend_angular:
    build:
      context: ./
      dockerfile: ./frontend_angular/Dockerfile
      args:
        # SSO URL for getting a token.
        SSO_OAUTH2: "https://adh6-dev.minet.net/api/oauth2.0"
        # URL of ADH6, the SSO will redirect to that URL after login.
        ADH6_URL: "https://adh6-dev.minet.net/dashboard" # Do not forget the trailing slash!
        BYPASS_AUTH: "false"
    expose:
      - "8443" # app does not start as root here
    volumes:
      # Make a bind mount so you can modify files in the container
      - type: bind
        source: "./frontend_angular/src"
        target: "/adh6/frontend_angular/src/"
        read_only: true
      # These are files that are generated in the dockerfile that should not be
      # read from the host disk.
      - "/adh6/frontend_angular/src/app/config"

  # api_server is the API that actually does action on the database.
  api_server:
    build:
      context: ./
      dockerfile: ./api_server/Dockerfile
      args:
        OAUTH2_BASE_PATH: "https://adh6-dev.minet.net/api/oauth2"
        AUTH_CONSENT_ADDRESS: "https://adh6-dev.minet.net/authorize"
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_DB_NAME: ${DATABASE_DB_NAME}
        GITLAB_ACCESS_TOKEN: ${GITLAB_ACCESS_TOKEN}
    links:
      - database
    expose:
      - "443"
    environment:
      ENVIRONMENT: "dev"
    volumes:
      # Make a bind mount so you can modify files in the container
      - type: bind
        source: "./api_server/src"
        target: "/adh6/api_server/src/"
        read_only: true
      
  # The reverse proxy is used to gather the api and the frontend behind the same
  # host. We can also use it to cache requests.
  reverse_proxy:
    build: 
      context: "./reverse_proxy"
      args:
        ADH6_URL: "adh6-dev.minet.net"
        API_HOST: "api_server"
        API_PORT: "443"
        # adh6.minet.net/... requests will be proxied to this IP/host + port.
        FRONTEND_HOST: "frontend_angular"
        FRONTEND_PORT: "8443"
    links:
      - frontend_angular
      - api_server
    ports:
      - "443:443"
      - "80:80" # Redirect to 443.
    command: ['nginx-debug', '-g', 'daemon off;'] # More logging!

  # The RDBMS of the project.
  database:
    build: "database"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "adh6"
      MYSQL_USER: "adh6"
      MYSQL_PASSWORD: "adh6_pass" # Please change this password on prod'.
    expose:
      - "3306"
