version: '3.2'
services:
  # frontend_angular is a web server that provides the JS to the clients.
  frontend_angular:
    container_name: adh6_frontend
    build:
      context: frontend_angular
      dockerfile: Dockerfile.dev
    expose:
      - "80" # app does not start as root here
    volumes:
      # Make a bind mount so you can modify files in the container
      - type: bind
        source: "./frontend_angular/src"
        target: "/adh6/frontend_angular/src/"
        read_only: true
  # api_server is the API that actually does action on the database.
  api_server:
    container_name: adh6_backend
    build: api_server
    links:
      - database
    expose:
      - "8080"
    environment:
      ENVIRONMENT: "development"
      OAUTH2_BASE_PATH: "https://cas.minet.net/oidc"
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB_NAME: ${DATABASE_DB_NAME}
      GITLAB_ACCESS_TOKEN: ${GITLAB_ACCESS_TOKEN}
     
  reverse_proxy:
    container_name: adh6_reverse_proxy
    build: reverse_proxy
    links:
      - frontend_angular
      - api_server
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./reverse_proxy:/etc/nginx/templates
    environment:
      ADH6_URL: "adh6-local.minet.net"
      API_HOST: "api_server" 
      API_PORT: "8080"        
      FRONTEND_HOST: "frontend_angular"
      FRONTEND_PORT: "80"
    command: ['nginx-debug', '-g', 'daemon off;']
  
  database:
    read_only: true
    container_name: adh6_database
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${DATABASE_DB_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/lib/mysql:rw
      - /tmp:rw
      - /run/mysqld/:rw
